language: c++
os: linux
dist: focal
services:
    - xvfb

env:
  matrix:
    - TRAVIS_NO_EMPTY_JOB=true

matrix:
  exclude:
    - env: TRAVIS_NO_EMPTY_JOB=true

  include:
    - env: COMPILER=g++ JOBS=1 TEST_TYPE=configure-gl TEST_LEVEL=minimal GL_LIBS=all-apis EAGINE_CLANG_TIDY=clang-tidy-10
      addons: 
        apt:
          packages:
            - python3
            - pkgconf
            - cmake
            - make
            - g++
            - clang-tidy-10
            - mesa-common-dev
            - libgl1-mesa-dev
            - libglew-dev
            - libglfw3-dev
            - libssl-dev
            - libpng-dev
            - libsystemd-dev
    - env: COMPILER=g++ JOBS=2 TEST_TYPE=ctest TEST_LEVEL=minimal GL_LIBS=default EAGINE_CLANG_TIDY=clang-tidy-10
      addons:
        apt:
          packages:
            - python3
            - pkgconf
            - cmake
            - make
            - g++
            - clang-tidy-10
            - libboost-test-dev
            - mesa-common-dev
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libglew-dev
            - libglfw3-dev
            - libssl-dev
            - libpng-dev
            - libsystemd-dev
            - libopenal-dev
            - libalut-dev
    - env: COMPILER=g++ JOBS=3 TEST_TYPE=everything TEST_LEVEL=basic GL_LIBS=all-apis EAGINE_CLANG_TIDY=clang-tidy-10
      addons:
        apt:
          packages:
            - python3
            - pkgconf
            - cmake
            - make
            - g++
            - clang-tidy-10
            - libboost-test-dev
            - mesa-common-dev
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libglew-dev
            - libglfw3-dev
            - libssl-dev
            - libpng-dev
            - libsystemd-dev
            - libopenal-dev
            - libalut-dev

script:
  - xvfb-run --auto-servernum ./tools/run_tests.py --max-jobs ${JOBS} --test-type=${TEST_TYPE} --test-level=${TEST_LEVEL} --gl-libs=${GL_LIBS} --config --cmake -DCMAKE_CXX_COMPILER=${COMPILER}

notifications:
  email: false
