ca_cert_path: /path/to/ca/certificate.pem
msg_bus:
    ssl_engine: pkcs11
    pkey_id: pkcs11:token=oglplus;object=oglplus-cert
    router:
        address: /tmp/eagine-msgbus.socket
        id_major : 1000
        id_count:  1000
        cert_path: /path/to/router/certificate.pem
        keep_running: true
        shutdown:
            verify: true
            delay: 60s
            max_age: 2500ms
    bridge:
        cert_path: /path/to/bridge/certificate.pem
        keep_running: true
        shutdown:
            verify: true
            delay: 60s
            max_age: 2500ms
    endpoint:
        cert_path: /path/to/endpoint/certificate.pem
    sudoku:
        helper:
            count: 16
