log:
    backend: network
    network:
        address: localhost:34917
ca_cert_path: /path/to/ca/certificate.pem
msg_bus:
    ssl_engine: pkcs11
    pkey_id: pkcs11:token=oglplus;object=oglplus-cert
    router:
        address: /tmp/eagine-msgbus.socket
        id_major : 1000
        id_count:  1000
        cert_path: /path/to/router/certificate.pem
        keep_running: true
        shutdown:
            verify: true
            delay: 60s
            max_age: 2500ms
    bridge:
        cert_path: /path/to/bridge/certificate.pem
        keep_running: true
        shutdown:
            verify: true
            delay: 60s
            max_age: 2500ms
    endpoint:
        cert_path: /path/to/endpoint/certificate.pem
    sudoku:
        helper:
            count: 16
        solver:
            rank: 4
            width: 256
            height: 256
            solution_timeout: 16min
            gui:
                tile_size: 8
application:
    video:
        provider: provider_name
        display: display_name
        device:
            index: 0
            kind: hardware
            path: /dev/dri/card0
        driver: driver_name
        samples: 1
        color_bits: 8
        alpha_bits: 8
        depth_bits: 24
        stencil_bits: 8
        fullscreen: false
        offscreen: true
    opengl:
        version:
            major: 3
            minor: 3
        prefer_es: false
        debug_context: false
        compatibility: false
    surface:
        width: 1280
        height: 800
    framedump:
        prefix: /path/to/dir
        color: byte
        depth: float
        stencil: none
